/* generated by @ankhorage/orchestrator-module-expo-localization */
import i18n from "i18next";
import { initReactI18next } from "react-i18next";

export type I18nResources = Record<string, { translation: Record<string, string> }>;

function normalizeLocale(requested: string, resources: I18nResources, fallback: string) {
  const supported = Object.keys(resources);

  if (supported.includes(requested)) return requested;

  const [base] = requested.split("-");
  if (base && supported.includes(base)) return base;

  if (supported.includes(fallback)) return fallback;

  return supported[0] ?? fallback;
}

export function initI18n(args: { locale: string; resources: I18nResources }) {
  const { locale: requestedLocale, resources } = args;
  const locale = normalizeLocale(requestedLocale, resources, __DEFAULT_LOCALE__);

  if (!i18n.isInitialized) {
    i18n.use(initReactI18next).init({
      resources,
      lng: locale,
      fallbackLng: __DEFAULT_LOCALE__,
      interpolation: { escapeValue: false },
      react: { useSuspense: false }
    });
    return i18n;
  }

  if (i18n.language !== locale) {
    void i18n.changeLanguage(locale);
  }

  return i18n;
}

export { i18n };
