/* generated by @ankhorage/orchestrator-module-expo-localization */
import { RuntimeRendererConfigProvider } from "@ankh/runtime";
import React, { useEffect, useMemo, useState } from "react";
import * as ExpoLocalization from "expo-localization";
import { useTranslation } from "react-i18next";

import { initI18n } from "./i18n";
import {
  createLocalizationActionHandlers,
  createLocalizationNodePropsResolver,
} from "./runtimeLocalization";

export interface LocalizationPluginConfig {
  defaultLocale?: string;
}

export function LocalizationPluginProvider(props: {
  children: React.ReactNode;
  config?: LocalizationPluginConfig;
}) {
  const { children, config } = props;

  const locales = ExpoLocalization.getLocales();
  const deviceLocale =
    (locales.length > 0 ? locales[0]?.languageTag : null) ??
    (ExpoLocalization as { locale?: string }).locale ??
    __DEFAULT_LOCALE__;

  const initialLocale = config?.defaultLocale ?? deviceLocale;
  const [currentLocale, setCurrentLocale] = useState<string>(initialLocale);

  useEffect(() => {
    const resources: Record<string, { translation: Record<string, string> }> = {
__RESOURCE_LINES__
    };

    initI18n({
      locale: currentLocale,
      resources
    });
  }, [currentLocale]);

  const { t, i18n } = useTranslation();

  useEffect(() => {
    if (i18n.language && i18n.language !== currentLocale) {
      setCurrentLocale(i18n.language);
    }
  }, [currentLocale, i18n.language]);

  const runtimeRendererConfig = useMemo(() => {
    const translate = i18n.isInitialized ? t : (key: string) => key;

    return {
      resolveNodeProps: createLocalizationNodePropsResolver(translate),
      actionHandlers: createLocalizationActionHandlers(i18n),
    };
  }, [i18n, i18n.isInitialized, i18n.language, t]);

  return (
    <RuntimeRendererConfigProvider value={runtimeRendererConfig}>
      {children}
    </RuntimeRendererConfigProvider>
  );
}
