/* generated by @ankhorage/orchestrator-module-expo-localization */
import type { RuntimeActionHandlers, RuntimeNodePropsResolver } from "@ankh/runtime";
import type { i18n as I18nInstance } from "i18next";

const LOCALIZED_PROP_PAIRS = [
  ["i18nKey", "text"],
  ["titleI18nKey", "title"],
  ["descriptionI18nKey", "description"],
  ["eyebrowI18nKey", "eyebrow"],
  ["labelI18nKey", "label"],
  ["helperTextI18nKey", "helperText"],
  ["errorTextI18nKey", "errorText"],
  ["metaI18nKey", "meta"],
  ["childrenI18nKey", "children"],
] as const;

function isNonEmptyString(value: unknown): value is string {
  return typeof value === "string" && value.length > 0;
}

function hasOwnProp(props: Record<string, unknown>, key: string) {
  return Object.prototype.hasOwnProperty.call(props, key);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function resolveLocalizedPropValue(args: {
  props: Record<string, unknown>;
  keyProp: string;
  targetProp: string;
  translate: (key: string) => string;
}): string | undefined {
  const { props, keyProp, targetProp, translate } = args;
  const key = props[keyProp];

  if (!isNonEmptyString(key)) {
    return undefined;
  }

  const translated = translate(key);
  if (isNonEmptyString(translated) && translated !== key) {
    return translated;
  }

  if (hasOwnProp(props, targetProp)) {
    return undefined;
  }

  return key;
}

function isSetLanguageAction(action: {
  type: string;
  payload?: unknown;
}): action is {
  type: "setLanguage";
  payload: { locale: string };
} {
  return (
    action.type === "setLanguage" &&
    isRecord(action.payload) &&
    isNonEmptyString(action.payload.locale)
  );
}

export function createLocalizationNodePropsResolver(
  translate: (key: string) => string,
): RuntimeNodePropsResolver {
  return ({ props }) => {
    let resolvedProps: Record<string, unknown> | undefined;

    for (const [keyProp, targetProp] of LOCALIZED_PROP_PAIRS) {
      const localizedValue = resolveLocalizedPropValue({
        props,
        keyProp,
        targetProp,
        translate,
      });

      if (localizedValue === undefined) {
        continue;
      }

      resolvedProps ??= { ...props };
      resolvedProps[targetProp] = localizedValue;
    }

    return resolvedProps ?? props;
  };
}

export function createLocalizationActionHandlers(
  i18n: Pick<I18nInstance, "changeLanguage">,
): RuntimeActionHandlers {
  return {
    setLanguage: ({ action }) => {
      if (!isSetLanguageAction(action)) {
        return;
      }

      void i18n.changeLanguage(action.payload.locale);
    },
  };
}
