/* generated by @ankhorage/orchestrator-module-expo-localization */
import { useTranslation } from "react-i18next";

export function useT(namespace: string = "translation") {
  const { t, i18n } = useTranslation(namespace);
  return { t, i18n };
}
