import type { WriteFileInstruction } from '@ankhorage/orchestrator';

const GENERATED_BY = '@ankhorage/orchestrator-module-expo-localization';

export function buildLocalizationWriteFiles(args: {
  defaultLocale: string;
  locales: string[];
  translations: Record<string, Record<string, string>>;
}): WriteFileInstruction[] {
  const { defaultLocale, locales, translations } = args;

  return [
    {
      path: 'src/plugins/localization/i18n.ts',
      content: makeI18nTs(defaultLocale),
      overwrite: true,
    },
    {
      path: 'src/plugins/localization/useT.ts',
      content: makeUseTTs(),
      overwrite: true,
    },
    {
      path: 'src/plugins/localization/LocalizationProvider.tsx',
      content: makeLocalizationProviderTsx(defaultLocale, locales),
      overwrite: true,
    },
    {
      path: 'src/plugins/localization/index.ts',
      content: makeBarrelIndexTs(),
      overwrite: true,
    },
    ...makeLocaleJsonFiles(locales, translations),
  ];
}

function makeLocaleJsonFiles(
  locales: string[],
  configTranslations: Record<string, Record<string, string>>,
): WriteFileInstruction[] {
  const defaultTranslations: Record<string, Record<string, string>> = {
    en: {
      app_title: 'My App',
      hello: 'Hello',
      system_overview: 'System Overview',
      'system-overview': 'System Overview',
    },
    de: {
      app_title: 'Meine App',
      hello: 'Hallo',
      system_overview: 'Systemübersicht',
      'system-overview': 'Systemübersicht',
    },
  };

  return locales.map((locale) => {
    const contentSource =
      configTranslations[locale] ??
      (locale.startsWith('de') ? defaultTranslations.de : defaultTranslations.en);

    return {
      path: `src/plugins/localization/locales/${locale}.json`,
      content: `${JSON.stringify(contentSource, null, 2)}\n`,
    };
  });
}

function makeI18nTs(defaultLocale: string): string {
  return `/* generated by ${GENERATED_BY} */
import i18n from "i18next";
import { initReactI18next } from "react-i18next";

export type I18nResources = Record<string, { translation: Record<string, string> }>;

function normalizeLocale(requested: string, resources: I18nResources, fallback: string) {
  const supported = Object.keys(resources);

  if (supported.includes(requested)) return requested;

  const [base] = requested.split("-");
  if (base && supported.includes(base)) return base;

  if (supported.includes(fallback)) return fallback;

  return supported[0] ?? fallback;
}

export function initI18n(args: { locale: string; resources: I18nResources }) {
  const { locale: requestedLocale, resources } = args;
  const locale = normalizeLocale(requestedLocale, resources, ${JSON.stringify(defaultLocale)});

  if (!i18n.isInitialized) {
    i18n.use(initReactI18next).init({
      resources,
      lng: locale,
      fallbackLng: ${JSON.stringify(defaultLocale)},
      interpolation: { escapeValue: false },
      react: { useSuspense: false }
    });
    return i18n;
  }

  if (i18n.language !== locale) {
    void i18n.changeLanguage(locale);
  }

  return i18n;
}

export { i18n };
`;
}

function makeUseTTs(): string {
  return `/* generated by ${GENERATED_BY} */
import { useTranslation } from "react-i18next";

export function useT(namespace: string = "translation") {
  const { t, i18n } = useTranslation(namespace);
  return { t, i18n };
}
`;
}

function makeLocalizationProviderTsx(defaultLocale: string, locales: string[]): string {
  const resourcesLines = locales
    .map(
      (locale) =>
        `      ${JSON.stringify(locale)}: { translation: require("./locales/${locale}.json") },`,
    )
    .join('\n');

  return `/* generated by ${GENERATED_BY} */
import React, { useEffect, useState } from "react";
import * as ExpoLocalization from "expo-localization";
import { useTranslation } from "react-i18next";

import { TranslationProvider } from "@ankhorage/surface";

import { initI18n } from "./i18n";

export interface LocalizationPluginConfig {
  defaultLocale?: string;
}

export function LocalizationPluginProvider(props: {
  children: React.ReactNode;
  config?: LocalizationPluginConfig;
}) {
  const { children, config } = props;

  const locales = ExpoLocalization.getLocales();
  const deviceLocale =
    (locales.length > 0 ? locales[0]?.languageTag : null) ??
    (ExpoLocalization as { locale?: string }).locale ??
    ${JSON.stringify(defaultLocale)};

  const initialLocale = config?.defaultLocale ?? deviceLocale;
  const [currentLocale, setCurrentLocale] = useState<string>(initialLocale);

  useEffect(() => {
    const resources: Record<string, { translation: Record<string, string> }> = {
${resourcesLines}
    };

    initI18n({
      locale: currentLocale,
      resources
    });
  }, [currentLocale]);

  const { t, i18n } = useTranslation();

  useEffect(() => {
    if (i18n.language && i18n.language !== currentLocale) {
      setCurrentLocale(i18n.language);
    }
  }, [currentLocale, i18n.language]);

  return (
    <TranslationProvider t={i18n.isInitialized ? t : (key: string) => key} i18n={i18n}>
      {children}
    </TranslationProvider>
  );
}
`;
}

function makeBarrelIndexTs(): string {
  return `/* generated by ${GENERATED_BY} */
export { LocalizationPluginProvider } from "./LocalizationProvider";
export { useT } from "./useT";
export { i18n } from "./i18n";
`;
}
